### ISSUE TITLE
what's this picture？ notr error but 

### ISSUE THREAD

**Issue by bianbian886** [nasa-gibs/onearth#104]
![image](https://user-images.githubusercontent.com/45083910/61692624-90d73780-ad60-11e9-8cde-b8df6c30c7dc.png)

**Comment by bianbian886** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<mrfgen_configuration>
 <date_of_data>20140606</date_of_data>
 <parameter_name>MORCR143LLDY</parameter_name>
 <input_dir>MORCR143LLDY/source_images</input_dir> 
 <output_dir>MORCR143LLDY/output_dir</output_dir>
 <working_dir>MORCR143LLDY/working_dir</working_dir>
 <logfile_dir>MORCR143LLDY/logfile_dir</logfile_dir>
 <mrf_empty_tile_filename>MORCR143LLDY/empty_tiles/Blank_RGB_512.jpg</mrf_empty_tile_filename>
 <mrf_blocksize>512</mrf_blocksize>
 <mrf_compression_type>JPEG</mrf_compression_type>
 <outsize>327680 163840</outsize>
 <overview_levels>2 4 8 16 32 64 128 256 512 1024</overview_levels>
 <overview_resampling>nearest</overview_resampling>
 <target_epsg>4326</target_epsg>
 <extents>-180,-90,180,90</extents>
 <colormap></colormap>
 <mrf_name>{$parameter_name}%Y%j_.mrf</mrf_name>
 <mrf_nocopy>true</mrf_nocopy>
 <mrf_merge>true</mrf_merge>
</mrfgen_configuration>

**Comment by bianbian886** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<LayerConfiguration>
 <Identifier>MORCR143LLDY</Identifier>
 <Title>MORCR143LLDY</Title>
 <FileNamePrefix>MORCR143LLDY</FileNamePrefix>
 <TiledGroupName>MORCR143LLDY tileset</TiledGroupName>
 <HeaderFileName>/etc/onearth/config/headers/MORCR143LLDYTTTTTTT_.mrf</HeaderFileName>
 <Compression>JPEG</Compression>
 <TileMatrixSet>EPSG4326_2km</TileMatrixSet>
 <EmptyTileSize offset="0">0</EmptyTileSize>
 <Projection>EPSG:4326</Projection> 
 <EnvironmentConfig>/etc/onearth/config/conf/environment_geographic.xml</EnvironmentConfig>
 <ArchiveLocation static="false" year="true" root="geographic">test_MORCR143LLDY</ArchiveLocation>
 <Time>DETECT/P1D</Time>
</LayerConfiguration>

**Comment by jtroberts** [comment]
This looks like a bad layer configuration. The TileMatrixSet (2km) is too small for the given MRF, which is likely 250m. The EmptyTileSize should not be "0" since an empty tile file is used.
