### ISSUE TITLE
How can I use this repository?

### ISSUE THREAD

**Issue by haozhen315** [nasa-gibs/onearth#163]
Hello!
NASA EOS and WorldView are great products, and I am excited to find that the back-end code is open-sourced. 
However, I want to ask that is this repository specially designed for NASA products or it is designed for others to use so that other people can build their own system? If it is the former case, I think it would be much harder to use the code...
Best,
Zhen

**Comment by jtroberts** [comment]
It was built for NASA GIBS/Worldview but other people can use the software to build their own system. Any geospatial data product that can be converted to the MRF format will work. Yes, it will be harder to use the code depending on how far your requirements deviate from the default configurations, which are based on GIBS.

**Comment by haozhen315** [comment]
I see. Thank you very much!
