### ISSUE TITLE
Invert tick labels for display on dark background in oe_generate_legend.py

### ISSUE THREAD

**Issue by srussking** [nasa-gibs/onearth#48]
Currently we are generating png's from the xml, but the labels are black, making them invisible on a black background. Is it possible to specify that you want the legend to appear white, not sure if this could be specified in the xml already and I just don't have it, or if this is not possible currently and I will need to hack the code to get it in there.

**Comment by mcechini** [comment]
My preference would to not have this in the colormap.xml since it's not really relevant to the data->image mapping that the colormap specifies.  Could be a flag/configuration value to the oe_generate_legend.py script though.

**Comment by srussking** [comment]
Cool, I think I have found the places I need, if I get around to this later today I will try to grab a fresh copy of oe_generate_legend and add that as an option, mine is getting a little hacky...
