### ISSUE TITLE
OnEarth and Object Storage

### ISSUE THREAD

**Issue by PacoDu** [nasa-gibs/onearth#66]
First of all thanks for OnEarth! A bit complicated to setup at first, but it works like a charm once we get through the configuration.

I was wondering if we could serve tiles from Object Storage like S3 and Swift (i.e. set archive location to a bucket like s3://archive-repo/)? Is this even feasible or it would involve too much delay ?

This would be awesome for scaling

**Comment by jtroberts** [comment]
We include support for serving tiles from S3 in OnEarth 2.0 via mod_mrf. It is still a work in progress. We found the performance with serving tiles from S3 to not be as good as a traditional file system, but we're looking at ways to improve. Any suggestions are welcome.

**Comment by lucianpls** [comment]
Take a look at https://github.com/lucianpls/mod_mrf, which depends on https://github.com/lucianpls/mod_receive.  You will also need to configure mod_proxy as a reverse proxy for the S3 or swift storage.
That configuration will allow serving tiles directly from an MRF stored in the object store, WMTS compatible.  For performance reasons, the MRF index file should still be local.
In this configuration it does one S3 request per tile request, so the latency and costs are predictable.

As you note, it will be quite a bit slower, at least from S3.  The server then becomes a reverse proxy that translates the tile requests into range requests, hiding the storage mechanism.  Scaling depends on what you mean by it:

- Latency of serving tiles from fast direct storage is a couple ms when the server is busy and the OS disk cache is warm.  With S3, the latency average is 60-70 ms, maybe a bit less when the server is busy.
- As a result, a single server using local storage can sustain 2 to 4 times more requests than a S3 based EC2 machine.  We are talking 50K req/sec compared with about 10K, either way unlikely to be seen in the real world.
- Of course, load-balanced EC2 machines could be added, to improve the throughput.  And add CloudFront or any other CDN caching, in front of the tile server, to improve latency.  

Overall, it is hard if not impossible to beat the performance of a server with local storage.  The only thing better with S3 is the available storage space.

**Comment by PacoDu** [comment]
I was speeking of scaling in terms of storage, this could be useful for archive of oldest tiles and serve the latest ones from a local storage. Thanks I'll take a look at mod_mrf and mod_receive !
