### ISSUE TITLE
WFS time filtering and map variable

### ISSUE THREAD

**Issue by PacoDu** [nasa-gibs/onearth#84]
I've setup a WFS endpoint with onearth but I've encountered some trouble:

- I have to specify the absolute path of the map file in my query otherwise wfs.cgi returns `msCGILoadMap(): Web application error. CGI variable "map" is not set.`. Is this a misconfiguration of my WFS endpoint ? Or is there at least any way to specify only the relative path to `MapfileDir` ? Relative path returns `Unable to access file. (epsg4326.map)` and it doesn't point to the DefaultMapfile without map variable.

This is the WFS endpoint configuration : 
```
# WFS Endpoint
<Directory "/usr/share/onearth/wfs/epsg4326">
    MapfileDir /usr/share/onearth/mapserver/
    DefaultMapfile epsg4326.map
    Options Indexes FollowSymLinks ExecCGI
    AllowOverride None
    Order allow,deny
    Allow from all
    AddHandler cgi-script .cgi
    Header set Access-Control-Allow-Origin *
</Directory>
```

- TIME is not managed by WFS endpoint ?? Time variable doesn't have any effect on the query result
`/wfs/epsg4326/wfs.cgi?request=GetFeature&service=WFS&version=2.0.0&typeNames=ms:test1&map=/usr/share/onearth/mapserver/epsg4326.map&time=2016-04-19T12:00:00Z` 

After reading some documentation I just found that WFS endpoint doesn't have a TIME management like WMS :( 
Is it possible to manage TIME with WFS properties and filter ? any solution for time dependent features ? 
My use case is for windpseed features (Serve GFS through WFS features for exemple)

**Comment by jtroberts** [comment]
I'm not sure what is wrong with your WFS endpoint configuration. It should work just like WMS. Does /usr/share/onearth/wfs/epsg4326/wfs.cgi exist? MapfileDir uses an absolute path.

We have not really tested WFS with TIME. However, WFS is just using Mapserver and there is support for WFS filtering (http://mapserver.org/ogc/filter_encoding.html). In theory, if your data file contains "time" as a property you could filter based on that.

**Comment by PacoDu** [comment]
Thanks for your answer I will try to use a time property and WFS filter.

My MapfileDir is absolute and wfs.cgi exists, I'll continue investigating this issue thanks !

**Comment by jtroberts** [comment]
Closing this ticket. @PacoDu let us know if you have further questions.
