### ISSUE TITLE
OE2 date / roadmap

### ISSUE THREAD

**Issue by PacoDu** [nasa-gibs/onearth#89]
Is there any roadmap available for OE2 ? or a release date ?

I'm really interested about this new version that seems to have a better approach for cloud configuration and deployment. 2.1.1 have been released since 10th of September and is tagged "testing only", could we have more informations about that ? (Why it is test only ? What have been tested and which part is considered unstable ?)

**Comment by jtroberts** [comment]
These are great questions. We’re currently targeting January for a stable version of OnEarth 2. We’ve been constantly evolving the configurations used for OnEarth in earlier 2.x versions, which means there have been a lot of incompatibility between test releases. A release candidate for OnEarth 2.2.0 will undergo user acceptance testing very soon and we’re hoping to release it once any discovered issues are resolved. Support for vectors is still missing from OnEarth 2.2.0 and support for WMS is still unstable.

I’ll put up a roadmap in the wiki section sometime soon to give a better sense of what we are planning. This has been mostly driven by the GIBS project migrating to use AWS, so the effort has revolved around those requirements. I would be delighted to have more community involvement to help make the software more generic and useful for more users.

**Comment by jtroberts** [comment]
I've started a wiki page here: https://github.com/nasa-gibs/onearth/wiki/Release-Plans
We can update it as time goes on.

**Comment by PacoDu** [comment]
Thanks !

We are going to test OE2 in our environment and give you some feedback. Our use case is mostly about WMTS subdaily raster and MVT layers. We are also really interested in S3 storage which is one of the main feature we are looking for in OE2.
